### ISSUE TITLE
Error to Build the sh2eb-elf- tool-chain

### ISSUE THREAD

**Issue by cdlt** [yaul-org/libyaul-build-scripts#5]
Compiling toolchain in Ubuntu 16.04.02 32 bits

In Build the sh2eb-elf- tool-chain
Running this line:
crosstool-ng/ct-ng build
[INFO ]  Performing some trivial sanity checks
[ERROR]  Don't set LD_LIBRARY_PATH. It screws up the build.
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@488]
[ERROR]  >>        called from: CT_TestAndAbort[scripts/functions@508]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@58]

Current command (unknown), exited with error code: 1
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    3  abort build

**Comment by cdlt** [comment]
Fix:
  "unset LD_LIBRARY_PATH"

**Comment by ijacquez** [comment]
Did you specifically have `LD_LIBRARY_PATH` n your environment?

**Comment by cdlt** [comment]
Yes, it was required for the installation of another sdk
